name: Render Keymap Layers

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "keymap_drawer.config.yml"

jobs:
  render:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      west_config_path: ""
      parse_args: "corne:'--layer-names Base Lower Raise Adjust'"
      draw_args: "corne:'-k crkbd/rev1 -l LAYOUT_split_3x6_3'"
      destination: artifact